//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetAbsenceAttendance
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", ConfigurationName="SetAbsenceAttendance.SetAbsenceAttendance_OS_SI")]
    public interface SetAbsenceAttendance_OS_SI
    {
        
        // CODEGEN: Generating message contract since the operation SetAbsenceAttendance_OS_SI is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SetAbsenceAttendance.SetAbsenceAttendance_OS_SIResponse SetAbsenceAttendance_OS_SI(SetAbsenceAttendance.SetAbsenceAttendance_OS_SIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SetAbsenceAttendance.SetAbsenceAttendance_OS_SIResponse> SetAbsenceAttendance_OS_SIAsync(SetAbsenceAttendance.SetAbsenceAttendance_OS_SIRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class SetAbsenceAttendanceRequest
    {
        
        private string startDateField;
        
        private string originalStartDateField;
        
        private string startTimeField;
        
        private string originalStartTimeField;
        
        private string endDateField;
        
        private string originalEndDateField;
        
        private string endTimeField;
        
        private string originalEndTimeField;
        
        private string additionalDataField;
        
        private string operationField;
        
        private string personnelNumberField;
        
        private string absenceAttendanceTypeField;
        
        private string originalAbsenceAttendanceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OriginalStartDate
        {
            get
            {
                return this.originalStartDateField;
            }
            set
            {
                this.originalStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OriginalStartTime
        {
            get
            {
                return this.originalStartTimeField;
            }
            set
            {
                this.originalStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string OriginalEndDate
        {
            get
            {
                return this.originalEndDateField;
            }
            set
            {
                this.originalEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string OriginalEndTime
        {
            get
            {
                return this.originalEndTimeField;
            }
            set
            {
                this.originalEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string AdditionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PersonnelNumber
        {
            get
            {
                return this.personnelNumberField;
            }
            set
            {
                this.personnelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string AbsenceAttendanceType
        {
            get
            {
                return this.absenceAttendanceTypeField;
            }
            set
            {
                this.absenceAttendanceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string OriginalAbsenceAttendanceType
        {
            get
            {
                return this.originalAbsenceAttendanceTypeField;
            }
            set
            {
                this.originalAbsenceAttendanceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class SetAbsenceAttendanceResponse
    {
        
        private SetAbsenceAttendanceResponseReturnStatus returnStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SetAbsenceAttendanceResponseReturnStatus ReturnStatus
        {
            get
            {
                return this.returnStatusField;
            }
            set
            {
                this.returnStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class SetAbsenceAttendanceResponseReturnStatus
    {
        
        private string statusTypeField;
        
        private string messageTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string StatusType
        {
            get
            {
                return this.statusTypeField;
            }
            set
            {
                this.statusTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MessageText
        {
            get
            {
                return this.messageTextField;
            }
            set
            {
                this.messageTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAbsenceAttendance_OS_SIRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", Order=0)]
        public SetAbsenceAttendance.SetAbsenceAttendanceRequest SetAbsenceAttendanceRequest_MT;
        
        public SetAbsenceAttendance_OS_SIRequest()
        {
        }
        
        public SetAbsenceAttendance_OS_SIRequest(SetAbsenceAttendance.SetAbsenceAttendanceRequest SetAbsenceAttendanceRequest_MT)
        {
            this.SetAbsenceAttendanceRequest_MT = SetAbsenceAttendanceRequest_MT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAbsenceAttendance_OS_SIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", Order=0)]
        public SetAbsenceAttendance.SetAbsenceAttendanceResponse SetAbsenceAttendanceResponse_MT;
        
        public SetAbsenceAttendance_OS_SIResponse()
        {
        }
        
        public SetAbsenceAttendance_OS_SIResponse(SetAbsenceAttendance.SetAbsenceAttendanceResponse SetAbsenceAttendanceResponse_MT)
        {
            this.SetAbsenceAttendanceResponse_MT = SetAbsenceAttendanceResponse_MT;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface SetAbsenceAttendance_OS_SIChannel : SetAbsenceAttendance.SetAbsenceAttendance_OS_SI, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class SetAbsenceAttendance_OS_SIClient : System.ServiceModel.ClientBase<SetAbsenceAttendance.SetAbsenceAttendance_OS_SI>, SetAbsenceAttendance.SetAbsenceAttendance_OS_SI
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SetAbsenceAttendance_OS_SIClient() : 
                base(SetAbsenceAttendance_OS_SIClient.GetDefaultBinding(), SetAbsenceAttendance_OS_SIClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HTTPS_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SetAbsenceAttendance_OS_SIClient(EndpointConfiguration endpointConfiguration) : 
                base(SetAbsenceAttendance_OS_SIClient.GetBindingForEndpoint(endpointConfiguration), SetAbsenceAttendance_OS_SIClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SetAbsenceAttendance_OS_SIClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SetAbsenceAttendance_OS_SIClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SetAbsenceAttendance_OS_SIClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SetAbsenceAttendance_OS_SIClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SetAbsenceAttendance_OS_SIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetAbsenceAttendance.SetAbsenceAttendance_OS_SIResponse SetAbsenceAttendance.SetAbsenceAttendance_OS_SI.SetAbsenceAttendance_OS_SI(SetAbsenceAttendance.SetAbsenceAttendance_OS_SIRequest request)
        {
            return base.Channel.SetAbsenceAttendance_OS_SI(request);
        }
        
        public SetAbsenceAttendance.SetAbsenceAttendanceResponse SetAbsenceAttendance_OS_SI(SetAbsenceAttendance.SetAbsenceAttendanceRequest SetAbsenceAttendanceRequest_MT)
        {
            SetAbsenceAttendance.SetAbsenceAttendance_OS_SIRequest inValue = new SetAbsenceAttendance.SetAbsenceAttendance_OS_SIRequest();
            inValue.SetAbsenceAttendanceRequest_MT = SetAbsenceAttendanceRequest_MT;
            SetAbsenceAttendance.SetAbsenceAttendance_OS_SIResponse retVal = ((SetAbsenceAttendance.SetAbsenceAttendance_OS_SI)(this)).SetAbsenceAttendance_OS_SI(inValue);
            return retVal.SetAbsenceAttendanceResponse_MT;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetAbsenceAttendance.SetAbsenceAttendance_OS_SIResponse> SetAbsenceAttendance.SetAbsenceAttendance_OS_SI.SetAbsenceAttendance_OS_SIAsync(SetAbsenceAttendance.SetAbsenceAttendance_OS_SIRequest request)
        {
            return base.Channel.SetAbsenceAttendance_OS_SIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetAbsenceAttendance.SetAbsenceAttendance_OS_SIResponse> SetAbsenceAttendance_OS_SIAsync(SetAbsenceAttendance.SetAbsenceAttendanceRequest SetAbsenceAttendanceRequest_MT)
        {
            SetAbsenceAttendance.SetAbsenceAttendance_OS_SIRequest inValue = new SetAbsenceAttendance.SetAbsenceAttendance_OS_SIRequest();
            inValue.SetAbsenceAttendanceRequest_MT = SetAbsenceAttendanceRequest_MT;
            return ((SetAbsenceAttendance.SetAbsenceAttendance_OS_SI)(this)).SetAbsenceAttendance_OS_SIAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://kmdpiprd.kmd.dk/XISOAPAdapter/MessageServlet?senderParty=&senderService=K" +
                        "MD_LPT_VACAB_Service&receiverParty=&receiverService=&interface=SetAbsenceAttenda" +
                        "nce_OS_SI&interfaceNamespace=urn%3Akmd.dk%3ALPT%3AVACAB%3Aexternal");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SetAbsenceAttendance_OS_SIClient.GetBindingForEndpoint(EndpointConfiguration.HTTPS_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SetAbsenceAttendance_OS_SIClient.GetEndpointAddress(EndpointConfiguration.HTTPS_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            HTTPS_Port,
        }
    }
}
